export enum RouteKey {
  WELCOME = "/",
  HOME = "/home",
  OUR_BRANDS = "/our-brands",
  SAN_FU_LOU = "/our-brands/san-fu-lou",
  SORAE = "/our-brands/sorae",
  SENS = "/our-brands/sens",
  DI_MAI = "/our-brands/di-mai",
  DELIVERY = "/delivery",
  NEWS = "/news",
  PROMOTION = "/promotion",
  COOPERATION = "/cooperation",
  CONTACT_US = "/contact-us",
  MEMBERSHIP = "/membership",
  CAREERS = "/careers",
  E_INVOICE = "/e-invoice",
  RESERVATION = "/reservations",
  LOGIN = "/login",
  REGISTER = "/register",
  POLICY_OPERATING = "/policy/operating",
  POLICY_SHIPPING = "/policy/shipping",
  POLICY_PAYMENT = "/policy/payment",
  POLICY_RETURN = "/policy/return",
}
